affiliatedData = {None: {'license number': '402R-00471', 'licensee': u'420 GREEN GENIE INC'},
 u'1136 YUMA': {'license number': '402R-00613', 'licensee': u'YUMA WAY LLC'},
 u'14er HOLISTICS': {'license number': '402R-00208',
                     'licensee': u'SUSTAINABLE HEALTH LLC'},
 u'1859': {'license number': '402R-00374', 'licensee': u'5B1S LLC'},
 u'1:11': {'license number': '402R-00581', 'licensee': u'1-11 LLC'},
 u'3D CANNABIS CENTER': {'license number': '402R-00248',
                         'licensee': u'3-D DENVERS DISCREET DISPENSARY LLC'},
 u'A CUT ABOVE': {'license number': '402R-00587',
                  'licensee': u'HOBBY FARMS LLC'},
 u'ACME HEALING CENTER': {'license number': '402R-00480',
                          'licensee': u'DURANGO HEALING CENTER LLC'},
 u'AFFINITY': {'license number': '402R-00519', 'licensee': u'RME GROUP LLC'},
 u'AJOYA': {'license number': '402R-00203',
            'licensee': u'COMPASSIONATE PAIN MANAGEMENT LLC'},
 u'ALPENGLOW BOTANICALS LLC': {'license number': '402R-00365',
                               'licensee': u'ALPENGLOW BOTANICALS LLC'},
 u'ALPENGLOW PREMIUM CANNABIS': {'license number': '402R-00074',
                                 'licensee': u'ALPENGLOW BOTANICALS LLC'},
 u'ALPINE WELLNESS': {'license number': '402R-00091',
                      'licensee': u'ALPINE WELLNESS LLC'},
 u'ALTITUDE AURORA': {'license number': '402R-00301',
                      'licensee': u'TREATMENTS UNLIMITED LLC'},
 u'ALTITUDE EAST': {'license number': '402R-00024',
                    'licensee': u'TREATMENTS UNLIMITED LLC'},
 u'ALTITUDE ORGANIC CANNABIS': {'license number': '402R-00394',
                                'licensee': u'MODERN MEDICINE LLC'},
 u'ALTITUDE WEST': {'license number': '402R-00011',
                    'licensee': u'MILE HIGH THERAPEUTIC NETWORK LLC'},
 u'AMSTERDAM CAFE': {'license number': '402R-00075',
                     'licensee': u'KAYAK CORP'},
 u'AROMA': {'license number': '402R-00550', 'licensee': u'TASTEBUDZ LLC'},
 u'ASCEND II': {'license number': '402R-00040', 'licensee': u'ASCEND II LLC'},
 u'B GOOD': {'license number': '402R-00132', 'licensee': u'BOTANACARE LLC'},
 u'BACK TO THE GARDEN HEALTH AND WELLNESS CENTER LLC': {'license number': '402R-00165',
                                                        'licensee': u'BACK TO THE GARDEN HEALTH & WELLNESS CENTER LLC'},
 u'BACKCOUNTRY CANNABIS COMPANY': {'license number': '402R-00228',
                                   'licensee': u'CRESTED BUTTE WELLNESS CENTER LLC'},
 u'BALLPARK HOLISTIC DISPENSARY': {'license number': '402R-00253',
                                   'licensee': u'BALLPARK HOLISTIC DISPENSARY CORP'},
 u'BEMINDFUL': {'license number': '402R-00085', 'licensee': u'WDG INC'},
 u'BEST DAY EVER': {'license number': '402R-00486', 'licensee': u'OSIRIS LLC'},
 u'BESTCOLORADOMEDS.ORG': {'license number': '402R-00154',
                           'licensee': u'MEDICAL MJ SUPPLY LLC'},
 u'BILLO': {'license number': '402R-00127',
            'licensee': u'GATSBY HOLDINGS LLC'},
 u'BLUE HERON DISPENSARY': {'license number': '402R-00483',
                            'licensee': u'VILLAGE RETAIL LLC'},
 u'BONFIRE CANNABIS': {'license number': '402R-00002',
                       'licensee': u'CENTRAL LLC'},
 u'BONFIRE CANNABIS COMPANY': {'license number': '402R-00574',
                               'licensee': u'HIGHWAY 40 LLC'},
 u'BOULDER BOTANICS': {'license number': '402R-00190',
                       'licensee': u'CROSSROADS WELLNESS LLC'},
 u'BOULDER MMJ': {'license number': '402R-00338',
                  'licensee': u'MMJ AMERICA INC'},
 u'BUD CELLAR': {'license number': '402R-00071', 'licensee': u'KAZIMER LLC'},
 u'BUD FARM': {'license number': '402R-00432',
               'licensee': u'WILLOW NORTH INC'},
 u'BUD HUT INC': {'license number': '402R-00463', 'licensee': u'BUD HUT INC'},
 u'BUDDY BOY': {'license number': '402R-00664',
                'licensee': u'3B FEDERAL1 LLC'},
 u'CANNA CABINET INC': {'license number': '402R-00690',
                        'licensee': u'EARTH SOLUTIONS INC'},
 u'CANNA CITY': {'license number': '402R-00698',
                 'licensee': u'PC HOLDINGS INC'},
 u'CANNABIS STATION': {'license number': '402R-00068',
                       'licensee': u'COMPASSIONATE CARE GIVERS INC'},
 u'CANNACO': {'license number': '402R-00371', 'licensee': u'CANNA COMPANY'},
 u'CANNASSEUR': {'license number': '402R-00689',
                 'licensee': u'LASER MANAGEMENT LLC'},
 u'CHRONIC THERAPY': {'license number': '402R-00217',
                      'licensee': u'BEDDOR CLAUDE LLC'},
 u'COLORADO CANNABIS CONNECTION': {'license number': '402R-00590',
                                   'licensee': u'JVT ENTERPRISES INC'},
 u'COLORADO CANNABIS EXCHANGE': {'license number': '402R-00702',
                                 'licensee': u'SOUTH PUEBLO LLC'},
 u'COLORADO GROW COMPANY': {'license number': '402R-00343',
                            'licensee': u'THE ACCEPTUS GROUP LLC'},
 u'COLORADO HARVEST COMPANY': {'license number': '402R-00077',
                               'licensee': u'HIGH COUNTRY SUPPLY LLC'},
 u'COLORADO WEEDERY': {'license number': '402R-00695',
                       'licensee': u'COLORADO ALTERNATIVE HEALTH CARE LTD'},
 u'COMPLETE RELEAF': {'license number': '402R-00703',
                      'licensee': u'COMPLETE RELEAF CO LLC'},
 u'CROSS GENETICS': {'license number': '402R-00596',
                     'licensee': u'CG INDUSTRY LLC'},
 u"DAMIAN MARLEY'S STONY HILL BY TRU CANNABIS": {'license number': '402R-00105',
                                                 'licensee': u'BTE LLC'},
 u'DANK': {'license number': '402R-00004', 'licensee': u'JGB VENTURES LLC'},
 u'DELILAH LLC': {'license number': '402R-00182', 'licensee': u'DELILAH LLC'},
 u'DEN-REC DENVER RECREATIONAL DISPENSARY': {'license number': '402R-00646',
                                             'licensee': u'SUMMIT WELLNESS'},
 u'DENREC DENVER RECREATIONAL DISPENSARY': {'license number': '402R-00133',
                                            'licensee': u'SUMMIT WELLNESS'},
 u'DENVER CLONE STORE': {'license number': '402R-00344',
                         'licensee': u'AMERICAN INDUSTRY LLC'},
 u'DENVER DISPENSARY': {'license number': '402R-00084',
                        'licensee': u'DENVER DISPENSARY LLC'},
 u'DENVER KUSH CLUB': {'license number': '402R-00026', 'licensee': u'DKC LLC'},
 u'DINO DISPENSARY': {'license number': '402R-00746',
                      'licensee': u'DINO DISPENSARY LLC'},
 u'DO CORTEZ': {'license number': '402R-00388',
                'licensee': u'DURANGO ORGANICS LLP'},
 u'DO CRESTED BUTTE': {'license number': '402R-00413',
                       'licensee': u'DURANGO ORGANICS LLP'},
 u'DOCS APOTHECARY': {'license number': '402R-00146',
                      'licensee': u'PHYSICIAN PREFERRED PRODUCTS LLC'},
 u'DOCTORS GARDEN': {'license number': '402R-00138',
                     'licensee': u'COLORADO PRODUCT SERVICES LLC'},
 u'DOCTORS ORDERS': {'license number': '402R-00039',
                     'licensee': u'DOCTORS ORDERS LLC'},
 u'DRIFT': {'license number': '402R-00586',
            'licensee': u'BG3 INVESTMENTS LLC'},
 u'DURANGO ORGANICS': {'license number': '402R-00243',
                       'licensee': u'DURANGO ORGANICS LLP'},
 u'DURANGO REC ROOM': {'license number': '402R-00530',
                       'licensee': u'DP & D HOLDINGS LLC'},
 u'EARLS': {'license number': '402R-00108',
            'licensee': u'JEM DUTCH ACRES LLC'},
 u'ECLIPSE CANNABIS COMPANY': {'license number': '402R-00734',
                               'licensee': u'A&A INVESTMENTS LLC'},
 u'ELEMENTS': {'license number': '402R-00198',
               'licensee': u'OPTIONS MEDICAL CENTER LLC'},
 u'ELEVATED STRAINS': {'license number': '402R-00749',
                       'licensee': u'WHISPER CONSULTING GROUP LLC'},
 u'ELITE ORGANICS': {'license number': '402R-00255',
                     'licensee': u'ELITE ORGANICS LLC'},
 u'ELK MOUNTAIN TRADING POST LLC': {'license number': '402R-00369',
                                    'licensee': u'ELK MOUNTAIN TRADING POST LLC'},
 u'EMERALD CITY': {'license number': '402R-00564',
                   'licensee': u'EMERALD CITY WELLNESS LLC'},
 u'EMERALD FIELDS': {'license number': '402R-00376',
                     'licensee': u'RESERVE1 LLC'},
 u'EUFLORA': {'license number': '402R-00707',
              'licensee': u'CO & RO PARTNERS LLC'},
 u'EVERBLOOM': {'license number': '402R-00010',
                'licensee': u'4095 SHELTER LLC'},
 u'FARAGOSI FARMS': {'license number': '402R-00421',
                     'licensee': u'FARAGOSI FARMS INC'},
 u'FIFTY 2 EIGHTY, LLC': {'license number': '402R-00685',
                          'licensee': u'ROCKY MOUNTAIN DANK LLC'},
 u'FIFTY2EIGHTY LLC': {'license number': '402R-00693',
                       'licensee': u'TOKIN TIPI LLC'},
 u'FINE TREES': {'license number': '402R-00597', 'licensee': u'BIG TOE LLC'},
 u'FLOYDS OF LEADVILLE': {'license number': '402R-00170',
                          'licensee': u'PBVILLE LLC'},
 u'FOX CANNABIS': {'license number': '402R-00192',
                   'licensee': u'FOX STREET WELLNESS LLC'},
 u'FREEDOM ROAD': {'license number': '402R-00496',
                   'licensee': u'FREEDOM ROAD GARDEN LTD'},
 u'FRESH BAKED': {'license number': '402R-00193',
                  'licensee': u'FRESH BAKED LLC'},
 u'FROSTED LEAF': {'license number': '402R-00187',
                   'licensee': u'ALPINE HERBAL WELLNESS LLC'},
 u'FROSTY LEAF': {'license number': '402R-00521', 'licensee': u'MISSKAT INC'},
 u'FROZEN SMOKE DISPENSARY': {'license number': '402R-00615',
                              'licensee': u'FROZEN SMOKE DISPENSARY LLC'},
 u'GANJA GOURMET': {'license number': '402R-00103',
                    'licensee': u'GANJA GOURMET LLC'},
 u'GENERATION HEALTH': {'license number': '402R-00218',
                        'licensee': u'PATIENTS PLUS LLC'},
 u'GM ENTERPRISE INC': {'license number': '402R-00062',
                        'licensee': u'GOLDEN MEDS INC'},
 u'GOLDEN LEAF': {'license number': '402R-00171',
                  'licensee': u'D AND C MEDICAL MARIJUANA LLC'},
 u'GOLDEN MEDS INC': {'license number': '402R-00430',
                      'licensee': u'GREEN AROUND YOU LLC'},
 u'GOOD CHEMISTRY': {'license number': '402R-00733', 'licensee': u'MHFS LLC'},
 u'GOOD EARTH MEDS': {'license number': '402R-00247',
                      'licensee': u'DELANY & ASSOCIATES LLC'},
 u'GREEN CROSS OF LONGMONT': {'license number': '402R-00728',
                              'licensee': u'ANAPORT ENTERPRISES LLC'},
 u'GREEN CROSS SILT': {'license number': '402R-00259',
                       'licensee': u'RIFLE REMEDIES LLC'},
 u'GREEN DRAGON COLORADO': {'license number': '402R-00038',
                            'licensee': u'CANNABIS KING LLC'},
 u'GREEN DREAM CANNABIS': {'license number': '402R-00553',
                           'licensee': u'HEALTH SERVICES LLC'},
 u'GREEN GRASS CENTRAL CITY': {'license number': '402R-00066',
                               'licensee': u'GREEN GRASS LLC'},
 u'GREEN MAN CANNABIS': {'license number': '402R-00152',
                         'licensee': u'GMC LLC'},
 u'GREEN TREE MEDICINALS': {'license number': '402R-00535',
                            'licensee': u'ANCIENT ALTERNATIVES LLC'},
 u'GREEN WORLD': {'license number': '402R-00249', 'licensee': u'GM INC'},
 u'GREENFIELDS': {'license number': '402R-00492',
                  'licensee': u'GREEN FIELDS LLC'},
 u'GROUNDSWELL': {'license number': '402R-00400',
                  'licensee': u'CG NETWORK LLC'},
 u'GROWHOUSE NORTHGLENN': {'license number': '402R-00529',
                           'licensee': u'WASHINGTON POINT MANAGEMENT LLC'},
 u'GS WAREHOUSE': {'license number': '402R-00488',
                   'licensee': u'LARSEN GROUP II LLC'},
 u'HARVEST HOUSE': {'license number': '402R-00406',
                    'licensee': u'APEX INDUSTRIES INC'},
 u'HASHISH HUT': {'license number': '402R-00538',
                  'licensee': u'WHITE PORCH LLC'},
 u'HEADQUARTERS CANNABIS CO': {'license number': '402R-00367',
                               'licensee': u'COLORADO HEALING LLC'},
 u'HEALING HOUSE': {'license number': '402R-00041',
                    'licensee': u'URBAN CANNABIS LLC'},
 u'HELPING HANDS HERBALS': {'license number': '402R-00236',
                            'licensee': u'JTR CAREGIVERS LLC'},
 u'HERBAL WELLNESS LLC': {'license number': '402R-00215',
                          'licensee': u'HERBAL WELLNESS LLC'},
 u'HERBAN UNDERGROUND': {'license number': '402R-00237',
                         'licensee': u'ABUNDANT HEALTH DENVER LLC'},
 u'HERBS 4 YOU': {'license number': '402R-00076',
                  'licensee': u'MAGNA MARKETING INC'},
 u'HIGH COUNTRY HEALING': {'license number': '402R-00095',
                           'licensee': u'TZ FINANCIAL LLC'},
 u'HIGH COUNTRY HEALING 8': {'license number': '402R-00405',
                             'licensee': u'VAIL BUD BREWERY LLC'},
 u'HIGH LEVEL HEALTH': {'license number': '402R-00082',
                        'licensee': u'DISCOUNT MEDICAL MARIJUANA LLC'},
 u'HIGH Q': {'license number': '402R-00332', 'licensee': u'HQ LLC'},
 u'HIGH Q PALISADE': {'license number': '402R-00714',
                      'licensee': u'HQ CLIFFS LLC'},
 u'HIGH STREET GROWERS LLC': {'license number': '402R-00164',
                              'licensee': u'HIGH STREET GROWERS LLC'},
 u'HIGH VALLEY ANTONITO RETAIL CANNABIS': {'license number': '402R-00482',
                                           'licensee': u'ACADEMY OF THE HEALING ARTS LLC'},
 u'HIGH VALLEY RETAIL CANNABIS': {'license number': '402R-00232',
                                  'licensee': u'ACADEMY OF THE HEALING ARTS LLC'},
 u'HIGH WEST CANNABIS': {'license number': '402R-00498',
                         'licensee': u'SHRED INVESTMENTS LLC'},
 u'HIGHER ELEVATION': {'license number': '402R-00692',
                       'licensee': u'CONSCIOUS CONNEXION LLC'},
 u'HIGHLAND HEALTH': {'license number': '402R-00372',
                      'licensee': u'SOUTHERN COLORADO THERAPEUTICS INC'},
 u'HIGHLINE': {'license number': '402R-00655', 'licensee': u'C3D CO'},
 u'HOUSE OF DANKNESS': {'license number': '402R-00044',
                        'licensee': u'RD INDUSTRIES II LLC'},
 u'IGADI': {'license number': '402R-00115', 'licensee': u'IGADI LTD'},
 u'INFINITE WELLNESS CENTER': {'license number': '402R-00235',
                               'licensee': u'GREEN MEADOWS WELLNESS LLC'},
 u'KARING KIND': {'license number': '402R-00176',
                  'licensee': u'KARING KIND LLC'},
 u'KARMACEUTICALS': {'license number': '402R-00744',
                     'licensee': u'KARMACEUTICALS LLC'},
 u'KAYA': {'license number': '402R-00515',
           'licensee': u'SOUTHWEST ALTERNATIVE CARE LLC'},
 u'KIND CARE OF COLORADO LLC': {'license number': '402R-00516',
                                'licensee': u'KIND CARE OF COLORADO LLC'},
 u'KIND LOVE': {'license number': '402R-00370', 'licensee': u'KIND LOVE LLC'},
 u'KRYSTALEAVES': {'license number': '402R-00688',
                   'licensee': u'CGFR GROUP INC'},
 u'KUSH GARDENS LLC': {'license number': '402R-00318',
                       'licensee': u'KUSH GARDENS LLC'},
 u"L'EAGLE": {'license number': '402R-00207',
              'licensee': u"L'EAGLE SERVICES LLC"},
 u'LEAF ON THE MESA': {'license number': '402R-00382',
                       'licensee': u'AMERICAN PRIDE GROWERS LLC'},
 u'LIFE FLOWER DISPENSARY LLC': {'license number': '402R-00481',
                                 'licensee': u'IEROS LLC'},
 u'LIGHTSHADE': {'license number': '402R-00163',
                 'licensee': u'COLORADO FARMS INC'},
 u'LIGHTSHADE LABS': {'license number': '402R-00684',
                      'licensee': u'FEDERAL HEIGHTS DISPENSARY LLC'},
 u'LIT': {'license number': '402R-00045',
          'licensee': u'MILE HIGH MEDICAL CANNABIS LLC'},
 u'LIVE GREEN CANNABIS': {'license number': '402R-00050',
                          'licensee': u'BUD MED HEALTH CENTERS LLC'},
 u'LIVWELL': {'license number': '402R-00166',
              'licensee': u'BEYOND BROADWAY LLC'},
 u'LOCAL PRODUCT OF COLORADO': {'license number': '402R-00543',
                                'licensee': u'HERBAL HEALTH LLC'},
 u'LODO WELLNESS CENTER': {'license number': '402R-00081',
                           'licensee': u'1617 WAZEE STREET LLC'},
 u'LUCKY MONKEY BUDS': {'license number': '402R-00476',
                        'licensee': u'DESSIMALS INC'},
 u'LUCKY SKY DISPENSARY': {'license number': '402R-00686',
                           'licensee': u'WASH PARK BOUTIQUE LLC'},
 u'LUCY SKY CANNABIS BOUTIQUE': {'license number': '402R-00159',
                                 'licensee': u'WASH PARK BOUTIQUE LLC'},
 u'MAGGIES FARM': {'license number': '402R-00725',
                   'licensee': u'VIRTUAL MARKETING LLC'},
 u'MAGGIES FARM LLC': {'license number': '402R-00222',
                       'licensee': u'WESTSIDE WELLNESS CENTER LLC'},
 u'MAGNOLIA ROAD CANNABIS CO': {'license number': '402R-00327',
                                'licensee': u'MAGNOLIA ROAD INC'},
 u'MAGNOLIA ROAD CANNABIS COMPANY': {'license number': '402R-00569',
                                     'licensee': u'MAGNOLIA ROAD INC'},
 u'MAIN STREET CANNABIS': {'license number': '402R-00523',
                           'licensee': u'MAIN STREET CANNABIS'},
 u'MEDICINE MAN': {'license number': '402R-00034',
                   'licensee': u'FUTUREVISION LTD'},
 u'MEDICINE MAN LONGMONT': {'license number': '402R-00724',
                            'licensee': u'MEDICINE MAN LONGMONT LLC'},
 u'MEDICINE MAN THORNTON': {'license number': '402R-00640',
                            'licensee': u'FUTUREVISION 2020 LLC'},
 u'MESA ORGANICS': {'license number': '402R-00514',
                    'licensee': u'MESA ORGANICS LTD'},
 u'MIGHTY TREE': {'license number': '402R-00600',
                  'licensee': u'SMOKED COLORADO INC'},
 u'MILE HIGH WELLNESS GREEN STREET': {'license number': '402R-00445',
                                      'licensee': u'MILE HIGH WELLNESS II LLC'},
 u'MINDFUL': {'license number': '402R-00290', 'licensee': u'3LP LLC'},
 u'MMJ AMERICA SHERIDAN': {'license number': '402R-00592',
                           'licensee': u'MMJ SHERIDAN LLC'},
 u'MMJ AMERICA UPTOWN': {'license number': '402R-00019',
                         'licensee': u'MILE HIGH MEDICAL LLC'},
 u'MOUNTAIN MEDICINIALS RETAIL CENTER': {'license number': '402R-00161',
                                         'licensee': u'MOUNTAIN MEDICINALS INC'},
 u'MR NICE GUYS': {'license number': '402R-00500',
                   'licensee': u'VITA MEDS LLC'},
 u'NATIVE ROOTS APOTHECARY': {'license number': '402R-00027',
                              'licensee': u'ALTERNATIVE MEDICINE ON THE MALL LLC'},
 u'NATIVE ROOTS ASPEN': {'license number': '402R-00379',
                         'licensee': u'RJJ ASPEN LLC'},
 u'NATIVE ROOTS BOULDER': {'license number': '402R-00173',
                           'licensee': u'BOULDER RX LLC'},
 u'NATIVE ROOTS DENVER AIRPORT': {'license number': '402R-00696',
                                  'licensee': u'RJJ TOWER LLC'},
 u'NATIVE ROOTS DILLON': {'license number': '402R-00434',
                          'licensee': u'RJJ DILLON LLC'},
 u'NATIVE ROOTS EDGEWATER': {'license number': '402R-00335',
                             'licensee': u'RJJ EDGEWATER LLC'},
 u'NATIVE ROOTS FRISCO': {'license number': '402R-00363',
                          'licensee': u'RJJ FRISCO LLC'},
 u'NATIVE ROOTS HIGHLANDS': {'license number': '402R-00368',
                             'licensee': u'RJJ HIGHLANDS LLC'},
 u'NATIVE ROOTS LITTLETON': {'license number': '402R-00380',
                             'licensee': u'RJJ SHERIDAN LLC'},
 u'NATIVE ROOTS LONGMONT': {'license number': '402R-00416',
                            'licensee': u'RJJ LONGMONT LLC'},
 u'NATIVE ROOTS NORTH DENVER': {'license number': '402R-00493',
                                'licensee': u'RJJ ADAMS LLC'},
 u'NATIVE ROOTS SANTA FE': {'license number': '402R-00484',
                            'licensee': u'RJJ SANTA FE LLC'},
 u'NATIVE ROOTS TRINIDAD': {'license number': '402R-00617',
                            'licensee': u'RJJ TRINIDAD LLC'},
 u'NATIVE ROOTS VAIL': {'license number': '402R-00221',
                        'licensee': u'J&R PARTNERS LLC'},
 u'NATIVE ROOTS WEST DENVER': {'license number': '402R-00049',
                               'licensee': u'RJJ MORRISON II LLC'},
 u'NATURAL REMEDIES': {'license number': '402R-00054',
                       'licensee': u'ORGANIC GREENS INC'},
 u'NATURAL SELECTIONS': {'license number': '402R-00417',
                         'licensee': u'AJO HOLDINGS LLC'},
 u"NATURE'S HERBS AND WELLNESS DTC": {'license number': '402R-00130',
                                      'licensee': u'ALTITUDE WELLNESS CENTER LLC'},
 u'NATURES HERBS AND WELLNESS CENTER III': {'license number': '402R-00735',
                                            'licensee': u'NATURES HERBS & WELLNESS CENTER III LLC'},
 u'NATURES KISS': {'license number': '402R-00659',
                   'licensee': u'NATURES KISS CANNABIS SERVICES HEALTH AND WELLNESS'},
 u'NATURES MEDICINE SALIDA': {'license number': '402R-00241',
                              'licensee': u'ECOMED LLC'},
 u'NEW BROADSTERDAM': {'license number': '402R-00148',
                       'licensee': u'HERBAL ALTERNATIVES LLC'},
 u'NORTHERN LIGHTS CANNABIS CO': {'license number': '402R-00043',
                                  'licensee': u'NORTHERN LIGHTS NATURALS LLC'},
 u'NORTHERN STANDARD': {'license number': '402R-00580',
                        'licensee': u'MONTEM PHARMLABS LIMITED'},
 u'OASIS CANNABIS SUPERSTORE': {'license number': '402R-00098',
                                'licensee': u'MEDICINAL WELLNESS CENTER LLC'},
 u'OPTIONS': {'license number': '402R-00184',
              'licensee': u'OPTIONS MEDICAL CENTER WR LLC'},
 u'ORGANIC ALTERNATIVES': {'license number': '402R-00220',
                           'licensee': u'ORGANIC ALTERNATIVES LLC'},
 u'PAGOSA CRAFT': {'license number': '402R-00667',
                   'licensee': u'JOE CAL ENTERPRISES INC'},
 u'PAGOSA THERAPEUTICS': {'license number': '402R-00263',
                          'licensee': u'J and J ENTERPRISES INC'},
 u'PANDO': {'license number': '402R-00005', 'licensee': u'GT VENTURES I LLC'},
 u'PEAK DISPENSARY': {'license number': '402R-00340',
                      'licensee': u'PEAK HOLDINGS GROUP LLC'},
 u"PIG N' WHISTLE": {'license number': '402R-00361',
                     'licensee': u'CANNABIS FOR HEALTH LLC'},
 u'PINK HOUSE CHERRY': {'license number': '402R-00710',
                        'licensee': u'MADISON ENTERPRISES LLC'},
 u'PLATTE VALLEY DISPENSARY': {'license number': '402R-00224',
                               'licensee': u'PLATTE VALLEY DISPENSARY LLC'},
 u'PRIMA CANNABIS COMPANY': {'license number': '402R-00179',
                             'licensee': u'PRIMA BRANDS LLC'},
 u'PRIMO CANNABIS': {'license number': '402R-00622',
                     'licensee': u'SAN LUIS VALLEY INDUSTRIES LLC'},
 u'PROHIBITION HERB': {'license number': '402R-00261',
                       'licensee': u'ANIMAS HERBAL WELLNESS CENTER INC'},
 u'PUEBLO WEST ORGANICS': {'license number': '402R-00123',
                           'licensee': u'PUEBLO WEST ORGANICS LLC'},
 u'PURE MARIJUANA DISPENSARY': {'license number': '402R-00438',
                                'licensee': u'505 CENTER LLC'},
 u'PURE MEDICAL DISPENSARY': {'license number': '402R-00396',
                              'licensee': u'COLORADO CANNABIS COMPANY LLC'},
 u'REDEYE RELEAF': {'license number': '402R-00121',
                    'licensee': u'GG MERCANTILE LLC'},
 u'REEFER MADNESS': {'license number': '402R-00104',
                     'licensee': u'DELTA-9 DELIGHTS LLC'},
 u'RIVERROCK': {'license number': '402R-00126',
                'licensee': u'CURE MEDICAL PHARM INC'},
 u'ROCKY MOUNTAIN BLAZE': {'license number': '402R-00444',
                           'licensee': u'GO RULE LLC'},
 u'ROCKY MOUNTAIN CANNABIS': {'license number': '402R-00509',
                              'licensee': u'GUNNISON CANNABIS LLC'},
 u'ROCKY MOUNTAIN HIGH': {'license number': '402R-00072',
                          'licensee': u'CMED LLC'},
 u'ROCKY MOUNTAIN ORGANICS': {'license number': '402R-00151',
                              'licensee': u'ALTERNATIVE HOLISTIC HEALING LLC'},
 u'ROCKY MOUNTAIN REMEDIES': {'license number': '402R-00136',
                              'licensee': u'RK ENTERPRISES LTD'},
 u'ROCKY ROAD AURORA': {'license number': '402R-00307',
                        'licensee': u'RRAW LLC'},
 u'ROCKY ROAD THORNTON': {'license number': '402R-00633',
                          'licensee': u'ROCKY ROAD REMEDIES LLC'},
 u'ROCKY ROAD VAIL': {'license number': '402R-00226',
                      'licensee': u'ROCKY ROAD REMEDIES LLC'},
 u'ROOTED': {'license number': '402R-00605',
             'licensee': u'STARRYNIGHT MANAGEMENT LLC'},
 u'ROOTSRX': {'license number': '402R-00487', 'licensee': u'RFSCA LLC'},
 u'ROYAL RESIN': {'license number': '402R-00540',
                  'licensee': u'ROYAL ASSET MANAGEMENT LLC'},
 u'SACRED SEED': {'license number': '402R-00037',
                  'licensee': u'CJJ SERVICES LLC'},
 u'SANTE ALTERNATIVE WELLNESS': {'license number': '402R-00336',
                                 'licensee': u'INDOOR HORTICULTURE CENTERS LLC'},
 u'SEDGWICK ALTERNATIVE RELIEF': {'license number': '402R-00223',
                                  'licensee': u'DACONO MEDS LLC'},
 u'SERENE WELLNESS WINTER PARK LLC': {'license number': '402R-00559',
                                      'licensee': u'SERENE WELLNESS V LLC'},
 u'SERGEANT GREEN LEAF': {'license number': '402R-00131',
                          'licensee': u'AREN & DAVES DREAM LLC'},
 u'SILVER STEM FINE CANNABIS': {'license number': '402R-00729',
                                'licensee': u'I&S LLC'},
 u'SILVERPEAK APOTHECARY': {'license number': '402R-00140',
                            'licensee': u'COOPER MASON VENTURES LLC'},
 u'SILVERTON GREEN WORKS': {'license number': '402R-00264',
                            'licensee': u'KENDALL MOUNTAIN LLC'},
 u'SIMPLY PURE': {'license number': '402R-00510',
                  'licensee': u'SIMPLY PURE COLORADO LLC'},
 u'SKM': {'license number': '402R-00748',
          'licensee': u'SOFA KING MEDICINAL WELLNESS PRODUCTS LLC'},
 u"SMOKEY'S": {'license number': '402R-00554',
               'licensee': u'GREEN MEDICALS WELLNESS CENTER #5 LLC'},
 u'SMOKEYS': {'license number': '402R-00169',
              'licensee': u'CANNABIS CARE WELLNESS CENTERS LLC'},
 u'SMOKINGUN APOTHECARY': {'license number': '402R-00262',
                           'licensee': u'SMOKING GUN LLC'},
 u'SOMA WELLNESS CENTER': {'license number': '402R-00205',
                           'licensee': u'PURE INDUSTRIES LLC'},
 u'SOUTH PARK FARMA': {'license number': '402R-00712',
                       'licensee': u'FRONT RANGE BOTANICAL LLC'},
 u'SOUTHWEST ALTERNATIVE CARE FOX ST': {'license number': '402R-00544',
                                        'licensee': u'D & D CONSULTING INC'},
 u'STARBUDS': {'license number': '402R-00722',
               'licensee': u'BROTHERS FOR LIFE LLC'},
 u'STARBUDS LONGMONT': {'license number': '402R-00708',
                        'licensee': u'LM MJC LLC'},
 u'STASH': {'license number': '402R-00160',
            'licensee': u'K.I.N.D. WELLNESS CENTER LLC'},
 u'STICKY BUDS BROADWAY': {'license number': '402R-00101',
                           'licensee': u'HEALTH DEPOT LLC'},
 u'STICKY BUDS COLFAX': {'license number': '402R-00238',
                         'licensee': u'HEALTH DEPOT LLC'},
 u'STICKY FINGERZ': {'license number': '402R-00656',
                     'licensee': u'MJM HOLDINGS LIMITED'},
 u'STICKY ICKYS': {'license number': '402R-00673',
                   'licensee': u'COLORADO GOLD LLP'},
 u'STRAWBERRY FIELDS': {'license number': '402R-00606',
                        'licensee': u'AHAB LLC'},
 u'SWEET LEAF': {'license number': '402R-00311',
                 'licensee': u'AJS AURORA LLC'},
 u'TELLURIDE BUD COMPANY': {'license number': '402R-00149',
                            'licensee': u'NEW WORLD ALTERNATIVE HEALTHCARE LLC'},
 u'TELLURIDE GREEN ROOM': {'license number': '402R-00134',
                           'licensee': u'TELLURIDE GREEN ROOM LLC'},
 u'TERRAPIN CARE STATION': {'license number': '402R-00269',
                            'licensee': u'APOGEE MANAGEMENT INC'},
 u'TETRAHYDROCENTER': {'license number': '402R-00059',
                       'licensee': u'TETRAHYDROCENTER LLC'},
 u'THE BUD DEPOT': {'license number': '402R-00358', 'licensee': u'RMIG LLC'},
 u'THE CLINIC HIGHLANDS': {'license number': '402R-00042',
                           'licensee': u'HIGHLANDS WELLNESS CENTER LLC'},
 u'THE CLINIC ON COLFAX': {'license number': '402R-00047',
                           'licensee': u'4625 E COLFAX LLC'},
 u'THE CLINIC ON COLORADO': {'license number': '402R-00079',
                             'licensee': u'HOLLY MEDICINAL SERVICES LLC'},
 u'THE COLFAX POT SHOP': {'license number': '402R-00030',
                          'licensee': u'NATURES CURE III LLC'},
 u'THE DAB BY NEXT HARVEST': {'license number': '402R-00137',
                              'licensee': u'ALCC LLC'},
 u'THE DELTA 9 DEPOT': {'license number': '402R-00612',
                        'licensee': u'EZRA ENTERPRISES INC'},
 u'THE DOOBIE SISTERS': {'license number': '402R-00563',
                         'licensee': u'SOUTHWEST SUNSHINE LLC'},
 u'THE FARM': {'license number': '402R-00210',
               'licensee': u'SKINNY PINEAPPLE INC'},
 u'THE FARMERS MARKET': {'license number': '402R-00409',
                         'licensee': u'THE OUNCE DEPOT LLC'},
 u'THE GREEN DEPOT': {'license number': '402R-00144',
                      'licensee': u'CO-AGRONOMICS LLC'},
 u'THE GREEN HOUSE': {'license number': '402R-00534',
                      'licensee': u'J and J ENTERPRISES INC'},
 u'THE GREEN JOINT': {'license number': '402R-00212',
                      'licensee': u'GREEN MEDICINE LLC'},
 u'THE GREEN ROOM': {'license number': '402R-00188',
                     'licensee': u'BOULDER ALTERNATIVE CARE LLC'},
 u'THE GREEN STOP': {'license number': '402R-00252',
                     'licensee': u'LARSEN GROUP LLC'},
 u'THE GREENERY': {'license number': '402R-00422',
                   'licensee': u'GREEN STREET DISPENSARY LLC'},
 u'THE GROWING KITCHEN': {'license number': '402R-00532',
                          'licensee': u'THE GROWING KITCHEN LLC'},
 u'THE HAPPY CAMPER CANNABIS COMPANY': {'license number': '402R-00245',
                                        'licensee': u'CCC INC'},
 u'THE HEALTH CENTER': {'license number': '402R-00747',
                        'licensee': u'GOLD & T LLC'},
 u'THE HERBAL ALTERNATIVE': {'license number': '402R-00353',
                             'licensee': u'DAVID KRZYSZTOFIAK LLC'},
 u'THE HERBAL CENTER': {'license number': '402R-00418',
                        'licensee': u'BK HOLDINGS LLC'},
 u'THE HIGHWAY': {'license number': '402R-00180', 'licensee': u'HCH 3 LLC'},
 u'THE HONEY CELLAR': {'license number': '402R-00199',
                       'licensee': u'LUW HOLDINGS LLC'},
 u'THE JOINT BY CANNABIS': {'license number': '402R-00230',
                            'licensee': u'CANNABIS CORP'},
 u'THE KIND CASTLE': {'license number': '402R-00526',
                      'licensee': u'THE CANNABIST CASTLE SUPERMARKET & DISPENSARY LOUNGE LLC'},
 u'THE KIND ROOM': {'license number': '402R-00012', 'licensee': u'DGS INC'},
 u'THE LEAF': {'license number': '402R-00669',
               'licensee': u'AMERICAN PRIDE GROWERS LLC'},
 u'THE LODGE': {'license number': '402R-00548', 'licensee': u'KTA LLC'},
 u'THE OTHER PLACE IS GREENER': {'license number': '402R-00645',
                                 'licensee': u'E&R RETAIL LLC'},
 u'THE SPOT': {'license number': '402R-00157',
               'licensee': u'COLORADO CANNABIS ASSOCIATES LLC'},
 u'THE SPOT 420': {'license number': '402R-00671',
                   'licensee': u'COLORADO CANNABIS ASSOCIATES LLC'},
 u'THE STATION': {'license number': '402R-00234', 'licensee': u'BUSHES LLC'},
 u'THE STONE DISPENSARY': {'license number': '402R-00494',
                           'licensee': u'STONE T.M.C. LLC'},
 u'THE TUMBLEWEED DISPENSARY': {'license number': '402R-00522',
                                'licensee': u'GREEN CROSS COLORADO LLC'},
 u'THE UNDERGROUND STATION LLC': {'license number': '402R-00616',
                                  'licensee': u'THE HERBAL GARDEN LLC'},
 u'THREE RIVERS DISPENSARY': {'license number': '402R-00556',
                              'licensee': u'THREE RIVERS DEVELOPMENT LLC'},
 u'TIMBERLINE HERBAL CLINIC AND WELLNESS CENTER LLC': {'license number': '402R-00087',
                                                       'licensee': u'TIMBERLINE HERBAL CLINIC AND WELLNESS CENTER LLC'},
 u'TREES': {'license number': '402R-00652', 'licensee': u'TDM LLC'},
 u'TRENCHTOWN': {'license number': '402R-00251', 'licensee': u'SISSCO LLC'},
 u'TRILL ALTERNATIVES': {'license number': '402R-00588',
                         'licensee': u'TRILL THERAPEUTICS LLC'},
 u'TRILL EVOLUTIONS': {'license number': '402R-00608',
                       'licensee': u'TRILL EVOLUTIONS LLC'},
 u'TUMBLEWEED': {'license number': '402R-00464',
                 'licensee': u'LYONS FINEST CONFIDENTIAL CARE LLC'},
 u'TUMBLEWEED CARBONDALE': {'license number': '402R-00467',
                            'licensee': u'TUMBLEWEED CARBONDALE LLC'},
 u'TUMBLEWEED DE BEQUE': {'license number': '402R-00704',
                          'licensee': u'TUMBLEWEED DE BEQUE LLC'},
 u'TUMBLEWEED DISPENSARY EDWARDS': {'license number': '402R-00257',
                                    'licensee': u'NEW HOPE WELLNESS CENTER LLC'},
 u'TUMBLEWEED EXPRESS': {'license number': '402R-00560',
                         'licensee': u'GREEN CROSS COLORADO LLC'},
 u'TUMBLEWEED FRISCO': {'license number': '402R-00124',
                        'licensee': u'TUMBLEWEED FRISCO LLC'},
 u'TWIN PEAKS DISPENSARY': {'license number': '402R-00730',
                            'licensee': u'YUMA WAY LLC'},
 u'UNIVERSAL HERBS': {'license number': '402R-00573',
                      'licensee': u'UNIVERSAL HERBS LLC'},
 u'URBAN DISPENSARY': {'license number': '402R-00458',
                       'licensee': u'URBAN HEALTH & WELLNESS INC'},
 u'VALLEY MEDS': {'license number': '402R-00513',
                  'licensee': u'VALLEY MEDS LLC'},
 u'VERDE NATURAL': {'license number': '402R-00662',
                    'licensee': u'ECO GREEN GROW LLC'},
 u'VERTICAL': {'license number': '402R-00545', 'licensee': u'VERTS LLC'},
 u'VILLAGE GREEN SOCIETY': {'license number': '402R-00200',
                            'licensee': u'COLORADO KIND CARE LLC'},
 u'WALKING RAVEN': {'license number': '402R-00058',
                    'licensee': u'WALKING RAVEN II LLC'},
 u'WHOLE MEDS': {'license number': '402R-00495', 'licensee': u'MJLQ LLC'},
 u'WOLF PAC CANNABIS': {'license number': '402R-00006',
                        'licensee': u'CONCENTRATE LLC'}}